### PR TITLE
Minor edits

### PR DESCRIPTION
**Pull request by katyhuff**
Hi folks, nice work. 

**Changes include:**
- I conducted a spellcheck. Depending on your text editor of choice, this is probably built in. Those of us in vi can use ":set spell" then move through the errors with "]s" and correct them by editing directly or by viewing suggestions with "z="
- added acronym capability with the glossaries package. Now there's no more keeping track of whether you've spell it out already. add new acronyms to the acros.tex file and use them in the text with \gls{ACRO}. It'll auto-expand on first use. Plurality is handled with \glspl .
- I updated the bib file in the repository based on the workflow I tried to describe before (probably poorly).    That is, I updatee the bib file based on updates in the group zotero library which add years to entries with missing  years, etc. The group zotero library now contains a directory at arfc/advanced-reactors/MSR/MSR-design. This is where new entries should be added. Exporting as .bib should result in approximately the same bib file for all users. The wikipedia reference is now missing because it was not found in Zotero. This can be added back easily by whomever cited it in the first place.
- Now that it has a year in the bib file, the tex citation of kophazi gets a year in the text, 2009.
-   I find the red and green box links created by hyperref very distracting, so I got rid of the boxes with 'hidelinks'. The links are still links though if you click on them. They just aren't surrounded by boxes.
- I'm fussy about using my full name on documents and I am happy as last author, so I changed Katy to Kathryn and moved myself in the author list to last.
-  most style guides prefer the reference within the sentence (e.g. before the period).
-  include packages ordering is always complicated by hyperref
- I've never heard this part of the reactor called anything except the 'downcomer', so I rewrote this sentence.
- neutron mesh -> neutronics mesh
- note about ultimate coupling goal

**Workflow from here:** 
Ideally, you can review this PR on GitHub, make comments about anything you think I should change in this PR, and when I've satisfied your concerns, you can merge the PR.

### CODE REVIEW

**Comment by katyhuff** [comment]
> I already had this workflow in place although perhaps somewhat
> convoluted. 

Where, in the arfc shared zotero space, is the directory where you were keeping all the references for this document? I couldn't find one, so when I wanted to correct the issue with a few of them missing years, I created a directory at arfc/advanced-reactors/MSR/MSR-design.

**Comment by katyhuff** [comment]
Relatedly, I don't see a reason to have references that are not kept in zotero. Anything can be saved in zotero (code items, wikipedia items, websites... ) so this zotero + non-zotero workflow seems unnecessary to me.

**Comment by lindsayad** [comment]
I was using the MSR/background folder. What's the difference between the 
MSR/background and MSR/MSR-design folders?

**Comment by lindsayad** [comment]
Fair enough. Still not enough background in Zotero to know it's 
capabilities. I suppose I should do some more research. We can 
definitely get rid of the multiple bibs then.

**Comment by katyhuff** [comment]
Ah. I see. So you were super close then, to what I intended. Sorry for misunderstanding.

It didn't even occur to me that the bib file was just an export from background. I assumed MSR-design.bib was curated just to include the things the two of you had read and intended to cite in the document some time. I think I created the background folder long ago, and I know you guys have been adding to it, so  it's got way more in it than this document needs. I assumed that wasn't your list and therefore just created a new folder with everything I saw in MSR-design.bib, assuming that was the more limited list -- so now, they're basically the same folder and neither is exactly the list of items to be cited in the document. 

Rather than including every possible paper that might be cited, the workflow that I think makes the most sense is to have a zotero directory that just contains the item actually cited in a document. So, when starting a document:
- Open zotero and create a directory titled as the root the bib file you want to include (e.g. mypaper.bib)
- Anything you know you want to cite in your document, drag those things into the directory (don't worry, drag is like copy in zotero)
- Export the folder as .bib (it will be called mypaper.bib) to the repository

When you or a collaborator wants to cite something that is not in the folder:
- Make sure the entity entry exists in Zotero. If not, then create one (ideally using your browser plugin)
- Drag the entry into the mypaper folder
- Export the file to the repository (it will overwrite mypaper.bib)

When you or a collaborator wants to change an entity in the folder (e.g. add a missing date):
- Navigate in Zotero to the entry 
- Edit the entry
- Export the mypaper folder as .bib to the repository (it will overwrite mypaper.bib)

To fix this mangled part of my pr, I propose do the following so that it jives with the ideal workflow:
- I'll remove all non-cited items from the MSR-design directory in Zotero. 
- I'll add a wikipedia item and a scale item
- I'll export the MSR-design directory as .bib to the repository
- I'll undo your (quite clever, sorry I didn't notice it!) zotero/non-zotero make solution
  
  Sound ok?

**Comment by lindsayad** [comment]
That sounds excellent

**Pull request merged**
